version: '3'
services: 
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nestjs:
    build: 
      context: .
      dockerfile: DockerFile
    environment: 
      - DATABASE_URL=${DATABASE_URL}
    ports: 
      - "3000:3000" # expose-to-the-world : only-in-the-docker
    depends_on: 
      - db
    volumes: 
      - .:/app
      - /app/node_modules
volumes:
  pgdata: